### ISSUE TITLE
reduce sidebar for more space for samples table

### ISSUE THREAD

**Issue by sadelokiki** [chanzuckerberg/idseq-web#913] opened 2018-03-14 19:16 UTC

**Comment by eggerdesigns** [comment] 2018-03-15 22:08
@sadelokiki @cyrielo isn't this a repro of 866

**Comment by cyrielo** [comment] 2018-03-17 14:00
Yes! Closing this because its a duplicate of #866 and the corresponding PR is #977

**Closed by cyrielo** 2018-03-17 14:00 UTC
Labels: to do
